# coding: utf-8

"""
    Amadeus Travel Innovation Sandbox

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 1.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from .address import Address
from .affiliate_flight_search_price import AffiliateFlightSearchPrice
from .affiliate_payout import AffiliatePayout
from .affiliate_search_meta import AffiliateSearchMeta
from .affiliate_search_response import AffiliateSearchResponse
from .affiliate_search_result import AffiliateSearchResult
from .airport import Airport
from .airport_autocomplete_response import AirportAutocompleteResponse
from .airport_information import AirportInformation
from .amenity import Amenity
from .amount import Amount
from .award import Award
from .car_reservation import CarReservation
from .car_reservation_booking_info import CarReservationBookingInfo
from .car_search_response import CarSearchResponse
from .car_search_result import CarSearchResult
from .carrier_info import CarrierInfo
from .carrier_meta import CarrierMeta
from .city_information import CityInformation
from .company import Company
from .contact import Contact
from .error import Error
from .extensive_train_search_response import ExtensiveTrainSearchResponse
from .extensive_train_search_result import ExtensiveTrainSearchResult
from .extreme_search_response import ExtremeSearchResponse
from .extreme_search_result import ExtremeSearchResult
from .fare import Fare
from .fare_restrictions import FareRestrictions
from .fees import Fees
from .flight_reservation_booking_info import FlightReservationBookingInfo
from .flight_reservation_bound import FlightReservationBound
from .flight_reservation_segment import FlightReservationSegment
from .flight_search_booking_info import FlightSearchBookingInfo
from .flight_search_bound import FlightSearchBound
from .flight_search_itinerary import FlightSearchItinerary
from .flight_search_price import FlightSearchPrice
from .flight_search_segment import FlightSearchSegment
from .flight_ticket import FlightTicket
from .flight_traffic_search_result import FlightTrafficSearchResult
from .frequent_traveler_card import FrequentTravelerCard
from .geolocation import Geolocation
from .hotel_property_response import HotelPropertyResponse
from .hotel_reservation import HotelReservation
from .hotel_reservation_booking_info import HotelReservationBookingInfo
from .hotel_room import HotelRoom
from .hotel_search_response import HotelSearchResponse
from .image import Image
from .image_size import ImageSize
from .infant import Infant
from .link import Link
from .location_response import LocationResponse
from .logos import Logos
from .low_fare_search_response import LowFareSearchResponse
from .low_fare_search_result import LowFareSearchResult
from .message import Message
from .nearest_airport import NearestAirport
from .other_reservation import OtherReservation
from .other_reservation_booking_info import OtherReservationBookingInfo
from .period_rate import PeriodRate
from .point_of_interest_city import PointOfInterestCity
from .point_of_interest_details import PointOfInterestDetails
from .point_of_interest_result import PointOfInterestResult
from .point_of_interest_result_grades import PointOfInterestResultGrades
from .points_of_interest_response import PointsOfInterestResponse
from .rail_service import RailService
from .rail_station_autocomplete_response import RailStationAutocompleteResponse
from .rail_station_response import RailStationResponse
from .rate import Rate
from .reservation import Reservation
from .restricted_rate import RestrictedRate
from .room_info import RoomInfo
from .station import Station
from .top_destinations_search_response import TopDestinationsSearchResponse
from .top_destinations_search_result import TopDestinationsSearchResult
from .top_searches_search_response import TopSearchesSearchResponse
from .top_searches_search_result import TopSearchesSearchResult
from .train_schedule_search_response import TrainScheduleSearchResponse
from .train_schedule_search_result import TrainScheduleSearchResult
from .train_search_itinerary import TrainSearchItinerary
from .train_search_pricing import TrainSearchPricing
from .train_search_segment import TrainSearchSegment
from .travel_record_header import TravelRecordHeader
from .travel_record_response import TravelRecordResponse
from .traveler import Traveler
from .vehicle import Vehicle
from .vehicle_info import VehicleInfo
