# coding: utf-8

"""
    Amadeus Travel Innovation Sandbox

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 1.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class CarrierInfo(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'logos': 'Logos',
        'name': 'str'
    }

    attribute_map = {
        'logos': 'logos',
        'name': 'name'
    }

    def __init__(self, logos=None, name=None):
        """
        CarrierInfo - a model defined in Swagger
        """

        self._logos = None
        self._name = None

        self.logos = logos
        self.name = name

    @property
    def logos(self):
        """
        Gets the logos of this CarrierInfo.
        Logos of the airline in a variety of sizes

        :return: The logos of this CarrierInfo.
        :rtype: Logos
        """
        return self._logos

    @logos.setter
    def logos(self, logos):
        """
        Sets the logos of this CarrierInfo.
        Logos of the airline in a variety of sizes

        :param logos: The logos of this CarrierInfo.
        :type: Logos
        """
        if logos is None:
            raise ValueError("Invalid value for `logos`, must not be `None`")

        self._logos = logos

    @property
    def name(self):
        """
        Gets the name of this CarrierInfo.
        Display name of the airline

        :return: The name of this CarrierInfo.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this CarrierInfo.
        Display name of the airline

        :param name: The name of this CarrierInfo.
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")

        self._name = name

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, CarrierInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
