# coding: utf-8

"""
    Amadeus Travel Innovation Sandbox

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 1.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class Contact(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'type': 'str',
        'purpose': 'str',
        'detail': 'str'
    }

    attribute_map = {
        'type': 'type',
        'purpose': 'purpose',
        'detail': 'detail'
    }

    def __init__(self, type=None, purpose=None, detail=None):
        """
        Contact - a model defined in Swagger
        """

        self._type = None
        self._purpose = None
        self._detail = None

        self.type = type
        if purpose is not None:
          self.purpose = purpose
        self.detail = detail

    @property
    def type(self):
        """
        Gets the type of this Contact.
        The method of contact, such as phone or fax.

        :return: The type of this Contact.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """
        Sets the type of this Contact.
        The method of contact, such as phone or fax.

        :param type: The type of this Contact.
        :type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")

        self._type = type

    @property
    def purpose(self):
        """
        Gets the purpose of this Contact.
        The reason or channel of that contact method. For example&colon; HOME, EMERGENCY, MOBILE.

        :return: The purpose of this Contact.
        :rtype: str
        """
        return self._purpose

    @purpose.setter
    def purpose(self, purpose):
        """
        Sets the purpose of this Contact.
        The reason or channel of that contact method. For example&colon; HOME, EMERGENCY, MOBILE.

        :param purpose: The purpose of this Contact.
        :type: str
        """

        self._purpose = purpose

    @property
    def detail(self):
        """
        Gets the detail of this Contact.
        How that contact should be used, eg. a phone number

        :return: The detail of this Contact.
        :rtype: str
        """
        return self._detail

    @detail.setter
    def detail(self, detail):
        """
        Sets the detail of this Contact.
        How that contact should be used, eg. a phone number

        :param detail: The detail of this Contact.
        :type: str
        """
        if detail is None:
            raise ValueError("Invalid value for `detail`, must not be `None`")

        self._detail = detail

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, Contact):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
