# coding: utf-8

"""
    Amadeus Travel Innovation Sandbox

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 1.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class FareRestrictions(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'refundable': 'bool',
        'change_penalties': 'bool'
    }

    attribute_map = {
        'refundable': 'refundable',
        'change_penalties': 'change_penalties'
    }

    def __init__(self, refundable=None, change_penalties=None):
        """
        FareRestrictions - a model defined in Swagger
        """

        self._refundable = None
        self._change_penalties = None

        self.refundable = refundable
        self.change_penalties = change_penalties

    @property
    def refundable(self):
        """
        Gets the refundable of this FareRestrictions.
        Indicates whether this fare is refundable under some circumstances. Note that a refund charge or penalty may apply

        :return: The refundable of this FareRestrictions.
        :rtype: bool
        """
        return self._refundable

    @refundable.setter
    def refundable(self, refundable):
        """
        Sets the refundable of this FareRestrictions.
        Indicates whether this fare is refundable under some circumstances. Note that a refund charge or penalty may apply

        :param refundable: The refundable of this FareRestrictions.
        :type: bool
        """
        if refundable is None:
            raise ValueError("Invalid value for `refundable`, must not be `None`")

        self._refundable = refundable

    @property
    def change_penalties(self):
        """
        Gets the change_penalties of this FareRestrictions.
        Indicates whether this fare allows the itinerary to be changed under some circumstances. Note that a change fee or penalty may apply

        :return: The change_penalties of this FareRestrictions.
        :rtype: bool
        """
        return self._change_penalties

    @change_penalties.setter
    def change_penalties(self, change_penalties):
        """
        Sets the change_penalties of this FareRestrictions.
        Indicates whether this fare allows the itinerary to be changed under some circumstances. Note that a change fee or penalty may apply

        :param change_penalties: The change_penalties of this FareRestrictions.
        :type: bool
        """
        if change_penalties is None:
            raise ValueError("Invalid value for `change_penalties`, must not be `None`")

        self._change_penalties = change_penalties

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, FareRestrictions):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
