# coding: utf-8

"""
    Amadeus Travel Innovation Sandbox

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 1.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class Fees(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'service_fees': 'str',
        'creditcard_fees': 'str'
    }

    attribute_map = {
        'service_fees': 'service_fees',
        'creditcard_fees': 'creditcard_fees'
    }

    def __init__(self, service_fees=None, creditcard_fees=None):
        """
        Fees - a model defined in Swagger
        """

        self._service_fees = None
        self._creditcard_fees = None

        if service_fees is not None:
          self.service_fees = service_fees
        if creditcard_fees is not None:
          self.creditcard_fees = creditcard_fees

    @property
    def service_fees(self):
        """
        Gets the service_fees of this Fees.
        The cost of any required service fees in addition to the total price

        :return: The service_fees of this Fees.
        :rtype: str
        """
        return self._service_fees

    @service_fees.setter
    def service_fees(self, service_fees):
        """
        Sets the service_fees of this Fees.
        The cost of any required service fees in addition to the total price

        :param service_fees: The service_fees of this Fees.
        :type: str
        """

        self._service_fees = service_fees

    @property
    def creditcard_fees(self):
        """
        Gets the creditcard_fees of this Fees.
        The cost of any fees for common credit cards, such as Visa or Mastercard, in addition to the total price

        :return: The creditcard_fees of this Fees.
        :rtype: str
        """
        return self._creditcard_fees

    @creditcard_fees.setter
    def creditcard_fees(self, creditcard_fees):
        """
        Sets the creditcard_fees of this Fees.
        The cost of any fees for common credit cards, such as Visa or Mastercard, in addition to the total price

        :param creditcard_fees: The creditcard_fees of this Fees.
        :type: str
        """

        self._creditcard_fees = creditcard_fees

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, Fees):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
