# coding: utf-8

"""
    Amadeus Travel Innovation Sandbox

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 1.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class FlightSearchItinerary(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'outbound': 'FlightSearchBound',
        'inbound': 'FlightSearchBound'
    }

    attribute_map = {
        'outbound': 'outbound',
        'inbound': 'inbound'
    }

    def __init__(self, outbound=None, inbound=None):
        """
        FlightSearchItinerary - a model defined in Swagger
        """

        self._outbound = None
        self._inbound = None

        self.outbound = outbound
        if inbound is not None:
          self.inbound = inbound

    @property
    def outbound(self):
        """
        Gets the outbound of this FlightSearchItinerary.
        The bound container for the flight information for bringing the traveler from the origin airport to the destination airport

        :return: The outbound of this FlightSearchItinerary.
        :rtype: FlightSearchBound
        """
        return self._outbound

    @outbound.setter
    def outbound(self, outbound):
        """
        Sets the outbound of this FlightSearchItinerary.
        The bound container for the flight information for bringing the traveler from the origin airport to the destination airport

        :param outbound: The outbound of this FlightSearchItinerary.
        :type: FlightSearchBound
        """
        if outbound is None:
            raise ValueError("Invalid value for `outbound`, must not be `None`")

        self._outbound = outbound

    @property
    def inbound(self):
        """
        Gets the inbound of this FlightSearchItinerary.
        The bound container for the flight information for bringing the traveler from the destination airport to the origin airport

        :return: The inbound of this FlightSearchItinerary.
        :rtype: FlightSearchBound
        """
        return self._inbound

    @inbound.setter
    def inbound(self, inbound):
        """
        Sets the inbound of this FlightSearchItinerary.
        The bound container for the flight information for bringing the traveler from the destination airport to the origin airport

        :param inbound: The inbound of this FlightSearchItinerary.
        :type: FlightSearchBound
        """

        self._inbound = inbound

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, FlightSearchItinerary):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
