# coding: utf-8

"""
    Amadeus Travel Innovation Sandbox

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 1.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class FrequentTravelerCard(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'issuer_type': 'str',
        'company_code': 'str',
        'card_number': 'str'
    }

    attribute_map = {
        'issuer_type': 'issuer_type',
        'company_code': 'company_code',
        'card_number': 'card_number'
    }

    def __init__(self, issuer_type=None, company_code=None, card_number=None):
        """
        FrequentTravelerCard - a model defined in Swagger
        """

        self._issuer_type = None
        self._company_code = None
        self._card_number = None

        self.issuer_type = issuer_type
        self.company_code = company_code
        self.card_number = card_number

    @property
    def issuer_type(self):
        """
        Gets the issuer_type of this FrequentTravelerCard.
        The type of organization that issued the card. This is an enumeration, possible values are AIRLINE, HOTEL_CHAIN, RENTAL_CAR_PROVIDER, RAILWAY.

        :return: The issuer_type of this FrequentTravelerCard.
        :rtype: str
        """
        return self._issuer_type

    @issuer_type.setter
    def issuer_type(self, issuer_type):
        """
        Sets the issuer_type of this FrequentTravelerCard.
        The type of organization that issued the card. This is an enumeration, possible values are AIRLINE, HOTEL_CHAIN, RENTAL_CAR_PROVIDER, RAILWAY.

        :param issuer_type: The issuer_type of this FrequentTravelerCard.
        :type: str
        """
        if issuer_type is None:
            raise ValueError("Invalid value for `issuer_type`, must not be `None`")

        self._issuer_type = issuer_type

    @property
    def company_code(self):
        """
        Gets the company_code of this FrequentTravelerCard.
        The identifying code of the issuer, within the context of its type. For example&colon; BA (and if the issuer type is AIRLINE, this indicates BA=British Airways).

        :return: The company_code of this FrequentTravelerCard.
        :rtype: str
        """
        return self._company_code

    @company_code.setter
    def company_code(self, company_code):
        """
        Sets the company_code of this FrequentTravelerCard.
        The identifying code of the issuer, within the context of its type. For example&colon; BA (and if the issuer type is AIRLINE, this indicates BA=British Airways).

        :param company_code: The company_code of this FrequentTravelerCard.
        :type: str
        """
        if company_code is None:
            raise ValueError("Invalid value for `company_code`, must not be `None`")

        self._company_code = company_code

    @property
    def card_number(self):
        """
        Gets the card_number of this FrequentTravelerCard.
        The identifying number (or string) marked on the card. For example&colon; 12345678.

        :return: The card_number of this FrequentTravelerCard.
        :rtype: str
        """
        return self._card_number

    @card_number.setter
    def card_number(self, card_number):
        """
        Sets the card_number of this FrequentTravelerCard.
        The identifying number (or string) marked on the card. For example&colon; 12345678.

        :param card_number: The card_number of this FrequentTravelerCard.
        :type: str
        """
        if card_number is None:
            raise ValueError("Invalid value for `card_number`, must not be `None`")

        self._card_number = card_number

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, FrequentTravelerCard):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
