# coding: utf-8

"""
    Amadeus Travel Innovation Sandbox

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 1.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class NearestAirport(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'airport': 'str',
        'airport_name': 'str',
        'city': 'str',
        'city_name': 'str',
        'state': 'str',
        'distance': 'float',
        'location': 'Geolocation',
        'aircraft_movements': 'int',
        'timezone': 'str'
    }

    attribute_map = {
        'airport': 'airport',
        'airport_name': 'airport_name',
        'city': 'city',
        'city_name': 'city_name',
        'state': 'state',
        'distance': 'distance',
        'location': 'location',
        'aircraft_movements': 'aircraft_movements',
        'timezone': 'timezone'
    }

    def __init__(self, airport=None, airport_name=None, city=None, city_name=None, state=None, distance=None, location=None, aircraft_movements=None, timezone=None):
        """
        NearestAirport - a model defined in Swagger
        """

        self._airport = None
        self._airport_name = None
        self._city = None
        self._city_name = None
        self._state = None
        self._distance = None
        self._location = None
        self._aircraft_movements = None
        self._timezone = None

        self.airport = airport
        self.airport_name = airport_name
        self.city = city
        self.city_name = city_name
        if state is not None:
          self.state = state
        self.distance = distance
        self.location = location
        if aircraft_movements is not None:
          self.aircraft_movements = aircraft_movements
        self.timezone = timezone

    @property
    def airport(self):
        """
        Gets the airport of this NearestAirport.
        The 3 letter IATA airport code of this given airport. You can use this as an input parameter for a low-fare flight search, to get more specific results than the city code, but inspiration search works best using the city code.

        :return: The airport of this NearestAirport.
        :rtype: str
        """
        return self._airport

    @airport.setter
    def airport(self, airport):
        """
        Sets the airport of this NearestAirport.
        The 3 letter IATA airport code of this given airport. You can use this as an input parameter for a low-fare flight search, to get more specific results than the city code, but inspiration search works best using the city code.

        :param airport: The airport of this NearestAirport.
        :type: str
        """
        if airport is None:
            raise ValueError("Invalid value for `airport`, must not be `None`")

        self._airport = airport

    @property
    def airport_name(self):
        """
        Gets the airport_name of this NearestAirport.
        The name of this airport, in UTF-8 format

        :return: The airport_name of this NearestAirport.
        :rtype: str
        """
        return self._airport_name

    @airport_name.setter
    def airport_name(self, airport_name):
        """
        Sets the airport_name of this NearestAirport.
        The name of this airport, in UTF-8 format

        :param airport_name: The airport_name of this NearestAirport.
        :type: str
        """
        if airport_name is None:
            raise ValueError("Invalid value for `airport_name`, must not be `None`")

        self._airport_name = airport_name

    @property
    def city(self):
        """
        Gets the city of this NearestAirport.
        The three letter <a href=\"https://en.wikipedia.org/wiki/International_Air_Transport_Association_airport_code\">IATA code</a> of the city of the city in which this airport is located.

        :return: The city of this NearestAirport.
        :rtype: str
        """
        return self._city

    @city.setter
    def city(self, city):
        """
        Sets the city of this NearestAirport.
        The three letter <a href=\"https://en.wikipedia.org/wiki/International_Air_Transport_Association_airport_code\">IATA code</a> of the city of the city in which this airport is located.

        :param city: The city of this NearestAirport.
        :type: str
        """
        if city is None:
            raise ValueError("Invalid value for `city`, must not be `None`")

        self._city = city

    @property
    def city_name(self):
        """
        Gets the city_name of this NearestAirport.
        The English name of the city in which this airport is located

        :return: The city_name of this NearestAirport.
        :rtype: str
        """
        return self._city_name

    @city_name.setter
    def city_name(self, city_name):
        """
        Sets the city_name of this NearestAirport.
        The English name of the city in which this airport is located

        :param city_name: The city_name of this NearestAirport.
        :type: str
        """
        if city_name is None:
            raise ValueError("Invalid value for `city_name`, must not be `None`")

        self._city_name = city_name

    @property
    def state(self):
        """
        Gets the state of this NearestAirport.
        The state code of this city, if applicable

        :return: The state of this NearestAirport.
        :rtype: str
        """
        return self._state

    @state.setter
    def state(self, state):
        """
        Sets the state of this NearestAirport.
        The state code of this city, if applicable

        :param state: The state of this NearestAirport.
        :type: str
        """

        self._state = state

    @property
    def distance(self):
        """
        Gets the distance of this NearestAirport.
        The distance in km from the point specified in the query, to this location

        :return: The distance of this NearestAirport.
        :rtype: float
        """
        return self._distance

    @distance.setter
    def distance(self, distance):
        """
        Sets the distance of this NearestAirport.
        The distance in km from the point specified in the query, to this location

        :param distance: The distance of this NearestAirport.
        :type: float
        """
        if distance is None:
            raise ValueError("Invalid value for `distance`, must not be `None`")

        self._distance = distance

    @property
    def location(self):
        """
        Gets the location of this NearestAirport.
          An object containing the longitude and latitude of the given airport.

        :return: The location of this NearestAirport.
        :rtype: Geolocation
        """
        return self._location

    @location.setter
    def location(self, location):
        """
        Sets the location of this NearestAirport.
          An object containing the longitude and latitude of the given airport.

        :param location: The location of this NearestAirport.
        :type: Geolocation
        """
        if location is None:
            raise ValueError("Invalid value for `location`, must not be `None`")

        self._location = location

    @property
    def aircraft_movements(self):
        """
        Gets the aircraft_movements of this NearestAirport.
        The annual number of aircraft movements at that airport.

        :return: The aircraft_movements of this NearestAirport.
        :rtype: int
        """
        return self._aircraft_movements

    @aircraft_movements.setter
    def aircraft_movements(self, aircraft_movements):
        """
        Sets the aircraft_movements of this NearestAirport.
        The annual number of aircraft movements at that airport.

        :param aircraft_movements: The aircraft_movements of this NearestAirport.
        :type: int
        """

        self._aircraft_movements = aircraft_movements

    @property
    def timezone(self):
        """
        Gets the timezone of this NearestAirport.
        The <a href=\"http://en.wikipedia.org/wiki/List_of_tz_database_time_zones\">Olson format</a> name of the timezone in which this airport is located

        :return: The timezone of this NearestAirport.
        :rtype: str
        """
        return self._timezone

    @timezone.setter
    def timezone(self, timezone):
        """
        Sets the timezone of this NearestAirport.
        The <a href=\"http://en.wikipedia.org/wiki/List_of_tz_database_time_zones\">Olson format</a> name of the timezone in which this airport is located

        :param timezone: The timezone of this NearestAirport.
        :type: str
        """
        if timezone is None:
            raise ValueError("Invalid value for `timezone`, must not be `None`")

        self._timezone = timezone

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, NearestAirport):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
