# coding: utf-8

"""
    Amadeus Travel Innovation Sandbox

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 1.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class PointsOfInterestResponse(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'current_city': 'PointOfInterestCity',
        'points_of_interest': 'list[PointOfInterestResult]'
    }

    attribute_map = {
        'current_city': 'current_city',
        'points_of_interest': 'points_of_interest'
    }

    def __init__(self, current_city=None, points_of_interest=None):
        """
        PointsOfInterestResponse - a model defined in Swagger
        """

        self._current_city = None
        self._points_of_interest = None

        if current_city is not None:
          self.current_city = current_city
        self.points_of_interest = points_of_interest

    @property
    def current_city(self):
        """
        Gets the current_city of this PointsOfInterestResponse.

        :return: The current_city of this PointsOfInterestResponse.
        :rtype: PointOfInterestCity
        """
        return self._current_city

    @current_city.setter
    def current_city(self, current_city):
        """
        Sets the current_city of this PointsOfInterestResponse.

        :param current_city: The current_city of this PointsOfInterestResponse.
        :type: PointOfInterestCity
        """

        self._current_city = current_city

    @property
    def points_of_interest(self):
        """
        Gets the points_of_interest of this PointsOfInterestResponse.

        :return: The points_of_interest of this PointsOfInterestResponse.
        :rtype: list[PointOfInterestResult]
        """
        return self._points_of_interest

    @points_of_interest.setter
    def points_of_interest(self, points_of_interest):
        """
        Sets the points_of_interest of this PointsOfInterestResponse.

        :param points_of_interest: The points_of_interest of this PointsOfInterestResponse.
        :type: list[PointOfInterestResult]
        """
        if points_of_interest is None:
            raise ValueError("Invalid value for `points_of_interest`, must not be `None`")

        self._points_of_interest = points_of_interest

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, PointsOfInterestResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
