# coding: utf-8

"""
    Amadeus Travel Innovation Sandbox

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 1.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class PointOfInterestCity(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'geoname_id': 'str',
        'location': 'Geolocation',
        'total_points_of_interest': 'int'
    }

    attribute_map = {
        'name': 'name',
        'geoname_id': 'geoname_id',
        'location': 'location',
        'total_points_of_interest': 'total_points_of_interest'
    }

    def __init__(self, name=None, geoname_id=None, location=None, total_points_of_interest=None):
        """
        PointOfInterestCity - a model defined in Swagger
        """

        self._name = None
        self._geoname_id = None
        self._location = None
        self._total_points_of_interest = None

        self.name = name
        if geoname_id is not None:
          self.geoname_id = geoname_id
        self.location = location
        self.total_points_of_interest = total_points_of_interest

    @property
    def name(self):
        """
        Gets the name of this PointOfInterestCity.
        The name of the location that was searched for

        :return: The name of this PointOfInterestCity.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this PointOfInterestCity.
        The name of the location that was searched for

        :param name: The name of this PointOfInterestCity.
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")

        self._name = name

    @property
    def geoname_id(self):
        """
        Gets the geoname_id of this PointOfInterestCity.
        The Geonames ID of the location that was searched for

        :return: The geoname_id of this PointOfInterestCity.
        :rtype: str
        """
        return self._geoname_id

    @geoname_id.setter
    def geoname_id(self, geoname_id):
        """
        Sets the geoname_id of this PointOfInterestCity.
        The Geonames ID of the location that was searched for

        :param geoname_id: The geoname_id of this PointOfInterestCity.
        :type: str
        """

        self._geoname_id = geoname_id

    @property
    def location(self):
        """
        Gets the location of this PointOfInterestCity.

        :return: The location of this PointOfInterestCity.
        :rtype: Geolocation
        """
        return self._location

    @location.setter
    def location(self, location):
        """
        Sets the location of this PointOfInterestCity.

        :param location: The location of this PointOfInterestCity.
        :type: Geolocation
        """
        if location is None:
            raise ValueError("Invalid value for `location`, must not be `None`")

        self._location = location

    @property
    def total_points_of_interest(self):
        """
        Gets the total_points_of_interest of this PointOfInterestCity.
        The total number of points_of_interest that YapQ has indexed for this city

        :return: The total_points_of_interest of this PointOfInterestCity.
        :rtype: int
        """
        return self._total_points_of_interest

    @total_points_of_interest.setter
    def total_points_of_interest(self, total_points_of_interest):
        """
        Sets the total_points_of_interest of this PointOfInterestCity.
        The total number of points_of_interest that YapQ has indexed for this city

        :param total_points_of_interest: The total_points_of_interest of this PointOfInterestCity.
        :type: int
        """
        if total_points_of_interest is None:
            raise ValueError("Invalid value for `total_points_of_interest`, must not be `None`")

        self._total_points_of_interest = total_points_of_interest

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, PointOfInterestCity):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
