# coding: utf-8

"""
    Amadeus Travel Innovation Sandbox

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 1.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class Rate(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'type': 'str',
        'price': 'Amount'
    }

    attribute_map = {
        'type': 'type',
        'price': 'price'
    }

    def __init__(self, type=None, price=None):
        """
        Rate - a model defined in Swagger
        """

        self._type = None
        self._price = None

        self.type = type
        self.price = price

    @property
    def type(self):
        """
        Gets the type of this Rate.
        The type or applicability period of rate being applied. For example&colon; DAILY, WEEKLY, WEEKEND.

        :return: The type of this Rate.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """
        Sets the type of this Rate.
        The type or applicability period of rate being applied. For example&colon; DAILY, WEEKLY, WEEKEND.

        :param type: The type of this Rate.
        :type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")

        self._type = type

    @property
    def price(self):
        """
        Gets the price of this Rate.
        The long name of the provider corresponding to the above code.

        :return: The price of this Rate.
        :rtype: Amount
        """
        return self._price

    @price.setter
    def price(self, price):
        """
        Sets the price of this Rate.
        The long name of the provider corresponding to the above code.

        :param price: The price of this Rate.
        :type: Amount
        """
        if price is None:
            raise ValueError("Invalid value for `price`, must not be `None`")

        self._price = price

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, Rate):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
