# coding: utf-8

"""
    Amadeus Travel Innovation Sandbox

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 1.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class Station(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'station_code': 'str',
        'station_name': 'str'
    }

    attribute_map = {
        'station_code': 'station_code',
        'station_name': 'station_name'
    }

    def __init__(self, station_code=None, station_name=None):
        """
        Station - a model defined in Swagger
        """

        self._station_code = None
        self._station_name = None

        self.station_code = station_code
        self.station_name = station_name

    @property
    def station_code(self):
        """
        Gets the station_code of this Station.
        ID of this rail station

        :return: The station_code of this Station.
        :rtype: str
        """
        return self._station_code

    @station_code.setter
    def station_code(self, station_code):
        """
        Sets the station_code of this Station.
        ID of this rail station

        :param station_code: The station_code of this Station.
        :type: str
        """
        if station_code is None:
            raise ValueError("Invalid value for `station_code`, must not be `None`")

        self._station_code = station_code

    @property
    def station_name(self):
        """
        Gets the station_name of this Station.
        Full name of this rail station.

        :return: The station_name of this Station.
        :rtype: str
        """
        return self._station_name

    @station_name.setter
    def station_name(self, station_name):
        """
        Sets the station_name of this Station.
        Full name of this rail station.

        :param station_name: The station_name of this Station.
        :type: str
        """
        if station_name is None:
            raise ValueError("Invalid value for `station_name`, must not be `None`")

        self._station_name = station_name

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, Station):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
