# coding: utf-8

"""
    Amadeus Travel Innovation Sandbox

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 1.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into sdk package
from .models.address import Address
from .models.affiliate_flight_search_price import AffiliateFlightSearchPrice
from .models.affiliate_payout import AffiliatePayout
from .models.affiliate_search_meta import AffiliateSearchMeta
from .models.affiliate_search_response import AffiliateSearchResponse
from .models.affiliate_search_result import AffiliateSearchResult
from .models.airport import Airport
from .models.airport_autocomplete_response import AirportAutocompleteResponse
from .models.airport_information import AirportInformation
from .models.amenity import Amenity
from .models.amount import Amount
from .models.award import Award
from .models.car_reservation import CarReservation
from .models.car_reservation_booking_info import CarReservationBookingInfo
from .models.car_search_response import CarSearchResponse
from .models.car_search_result import CarSearchResult
from .models.carrier_info import CarrierInfo
from .models.carrier_meta import CarrierMeta
from .models.city_information import CityInformation
from .models.company import Company
from .models.contact import Contact
from .models.error import Error
from .models.extensive_train_search_response import ExtensiveTrainSearchResponse
from .models.extensive_train_search_result import ExtensiveTrainSearchResult
from .models.extreme_search_response import ExtremeSearchResponse
from .models.extreme_search_result import ExtremeSearchResult
from .models.fare import Fare
from .models.fare_restrictions import FareRestrictions
from .models.fees import Fees
from .models.flight_reservation_booking_info import FlightReservationBookingInfo
from .models.flight_reservation_bound import FlightReservationBound
from .models.flight_reservation_segment import FlightReservationSegment
from .models.flight_search_booking_info import FlightSearchBookingInfo
from .models.flight_search_bound import FlightSearchBound
from .models.flight_search_itinerary import FlightSearchItinerary
from .models.flight_search_price import FlightSearchPrice
from .models.flight_search_segment import FlightSearchSegment
from .models.flight_ticket import FlightTicket
from .models.flight_traffic_search_result import FlightTrafficSearchResult
from .models.frequent_traveler_card import FrequentTravelerCard
from .models.geolocation import Geolocation
from .models.hotel_property_response import HotelPropertyResponse
from .models.hotel_reservation import HotelReservation
from .models.hotel_reservation_booking_info import HotelReservationBookingInfo
from .models.hotel_room import HotelRoom
from .models.hotel_search_response import HotelSearchResponse
from .models.image import Image
from .models.image_size import ImageSize
from .models.infant import Infant
from .models.link import Link
from .models.location_response import LocationResponse
from .models.logos import Logos
from .models.low_fare_search_response import LowFareSearchResponse
from .models.low_fare_search_result import LowFareSearchResult
from .models.message import Message
from .models.nearest_airport import NearestAirport
from .models.other_reservation import OtherReservation
from .models.other_reservation_booking_info import OtherReservationBookingInfo
from .models.period_rate import PeriodRate
from .models.point_of_interest_city import PointOfInterestCity
from .models.point_of_interest_details import PointOfInterestDetails
from .models.point_of_interest_result import PointOfInterestResult
from .models.point_of_interest_result_grades import PointOfInterestResultGrades
from .models.points_of_interest_response import PointsOfInterestResponse
from .models.rail_service import RailService
from .models.rail_station_autocomplete_response import RailStationAutocompleteResponse
from .models.rail_station_response import RailStationResponse
from .models.rate import Rate
from .models.reservation import Reservation
from .models.restricted_rate import RestrictedRate
from .models.room_info import RoomInfo
from .models.station import Station
from .models.top_destinations_search_response import TopDestinationsSearchResponse
from .models.top_destinations_search_result import TopDestinationsSearchResult
from .models.top_searches_search_response import TopSearchesSearchResponse
from .models.top_searches_search_result import TopSearchesSearchResult
from .models.train_schedule_search_response import TrainScheduleSearchResponse
from .models.train_schedule_search_result import TrainScheduleSearchResult
from .models.train_search_itinerary import TrainSearchItinerary
from .models.train_search_pricing import TrainSearchPricing
from .models.train_search_segment import TrainSearchSegment
from .models.travel_record_header import TravelRecordHeader
from .models.travel_record_response import TravelRecordResponse
from .models.traveler import Traveler
from .models.vehicle import Vehicle
from .models.vehicle_info import VehicleInfo

# import apis into sdk package
from .apis.default_api import DefaultApi

# import ApiClient
from .api_client import ApiClient

from .configuration import Configuration

configuration = Configuration()
