# coding: utf-8

"""
    Amadeus Travel Innovation Sandbox

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 1.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.hotel_room import HotelRoom


class TestHotelRoom(unittest.TestCase):
    """ HotelRoom unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHotelRoom(self):
        """
        Test HotelRoom
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.hotel_room.HotelRoom()
        pass


if __name__ == '__main__':
    unittest.main()
