# coding: utf-8

"""
    Amadeus Travel Innovation Sandbox

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 1.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """ DefaultApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.default_api.DefaultApi()

    def tearDown(self):
        pass

    def test_airport_autocomplete(self):
        """
        Test case for airport_autocomplete

        Airport Autocomplete - Find an IATA location code for flight search based on a city or airport name using the term parameter. By only using the country parameter, this API is also able to find all the IATA location codes associated with a country. Both term and country parameters can be used together to filter the results accordingly. The API is fully JQuery-Autocomplete compatible to enable you to quickly build a drop-down list for your users to find the right airport easily.
        """
        pass

    def test_car_rental_airport_search(self):
        """
        Test case for car_rental_airport_search

        Car Rental Airport Search - Find car rental providers and rates when you provide an airport code, as well as the pick-up and drop-off dates. Optional parameters such as currency and rental provider codes are also available and can be used to narrow down the results. This API is an ideal pairing with the flight and hotel search to provide ground transportation options at the destination.
        """
        pass

    def test_car_rental_geosearch(self):
        """
        Test case for car_rental_geosearch

        Car Rental Geosearch - Locate car rental providers and available vehicles when you define a circular area with one coordinate and radius, as well as the pick-up and drop-off dates. Optional parameters such as currency and rental provider codes are also available and can be used to narrow down the results. This API is an ideal pairing with the flight and hotel search to provide ground transportation options at the destination.
        """
        pass

    def test_flight_affiliate_search(self):
        """
        Test case for flight_affiliate_search

        Flight Affiliate Search - Use Travel Audience Connect's affiliate network API to search flights from our list of partners and provides deep-links to allow the user to book directly on the airline website.
        """
        pass

    def test_flight_extensive_search(self):
        """
        Test case for flight_extensive_search

        Flight Extensive Search - Build travel searches based on very flexible and open range of dates. You can use it to answer questions such as \"When is the best date to fly...\".  It's built on Amadeus' Featured Results technology, which returns thousands of results (prices, itineraries and dates) in a matter of milliseconds. Results are available over half a calendar year with a 1 to 15 day stay duration
        """
        pass

    def test_flight_inspiration_search(self):
        """
        Test case for flight_inspiration_search

        Flight Inspiration Search - Go beyond the traditional search by origin, destination and dates to meet the needs of travelers looking for suggestions and a search experience that reflects the way they choose their trip. This can help you answer the question \"Where can I go within a given travel budget?\"
        """
        pass

    def test_flight_low_fare_search(self):
        """
        Test case for flight_low_fare_search

        Flight Low-Fare Search - Find the cheapest one way or return itineraries and fares between two airports at specific dates.
        """
        pass

    def test_flight_traffic_api(self):
        """
        Test case for flight_traffic_api

        Flight Traffic API - Find the true origin and destination traffic summary between two journey points over a specified period. This can help you answer questions like \"What cities are people coming from to visit Los Angeles between January through April of 2015\"
        """
        pass

    def test_hotel_airport_search(self):
        """
        Test case for hotel_airport_search

        Hotel Airport Search - Locate the cheapest available rooms near a given airport, for a given stay period. This API is ideal if you want to connect flight and hotels. Provide an IATA airport code, as well as the check-in and check-out dates, and get a list of up to 140 properties (names, codes, image, amenities) with their locations and rates. Optional parameters such as currency and maximum rates, amenities or hotel chain codes are also available and can be used to narrow down the results. More optional parameters such as show_sold_out & rooms can be used to show sold out rooms and all available rooms.
        """
        pass

    def test_hotel_geosearch_by_box(self):
        """
        Test case for hotel_geosearch_by_box

        Hotel Geosearch by box - Locate the cheapest available rooms within a given rectangular region for a given stay period. It's ideal for displaying results on a map.
        """
        pass

    def test_hotel_geosearch_by_circle(self):
        """
        Test case for hotel_geosearch_by_circle

        Hotel Geosearch by Circle API - Locate the cheapest available rooms within a given radius of a defined point for a given stay period.
        """
        pass

    def test_hotel_property_code_search(self):
        """
        Test case for hotel_property_code_search

        Hotel Property Code Search - Find out more room and rate information once you have found your preferred hotel.
        """
        pass

    def test_location_information(self):
        """
        Test case for location_information

        Location Information - Find more information about any IATA city or airport location code. With this API, you can find information such as city and airport names and locations, as well as information on timezones and airport usage.
        """
        pass

    def test_nearest_relevant_airport(self):
        """
        Test case for nearest_relevant_airport

        Nearest Relevant Airport - Find the most useful nearby airport to a given location.
        """
        pass

    def test_rail_station_autocomplete(self):
        """
        Test case for rail_station_autocomplete

        Rail Station Autocomplete - Transform user input into a unique rail station code. Currently only French and Italian stations are supported.
        """
        pass

    def test_rail_station_information(self):
        """
        Test case for rail_station_information

        Rail-Station Information - Retrieve the rail station information corresponding to an Amadeus UIC rail station ID. Currently only French and Italian stations are supported.
        """
        pass

    def test_top_flight_destinations(self):
        """
        Test case for top_flight_destinations

        Top Flight Destinations - Find the most popular flight destinations from an origin during a period. This can help you answer questions like \"Where are most people going to from Paris during the month of September?\"
        """
        pass

    def test_top_flight_searches(self):
        """
        Test case for top_flight_searches

        Top Flight Searches - Find the most popular flight searches from an origin in a during given search period. This can help you answer questions like \"Where are people looking to travel from Paris during the month of September?\"
        """
        pass

    def test_train_extensive_search(self):
        """
        Test case for train_extensive_search

        Train Extensive Search - Provides multi-day availability and a variety of schedule and pricing options to travel to your destination instantly. Supports SNCF French trains only.
        """
        pass

    def test_train_schedule_search(self):
        """
        Test case for train_schedule_search

        Train Schedule Search - Suggest destinations from your chosen departure station. Supports SNCF French Rail only.
        """
        pass

    def test_travel_record_retrieve(self):
        """
        Test case for travel_record_retrieve

        Travel Record Retrieve - Enable travelers to explore the details of their journeys stored in the Amadeus system using our Retrieve Travel Record API.
        """
        pass

    def test_yap_q_city_name_search(self):
        """
        Test case for yap_q_city_name_search

        YapQ City Name Search - Find landmarks and attractions in a given city.
        """
        pass

    def test_yap_q_geosearch(self):
        """
        Test case for yap_q_geosearch

        YapQ Geosearch - Find landmarks and attractions near a given point.
        """
        pass


if __name__ == '__main__':
    unittest.main()
